name: 'Run JS Code Checks'
description: 'Runs eslint and tests if available'

inputs:
  linting:
    description: 'Should run linting'
    required: false
    default: 'false'
  tests:
    description: 'Should run tests'
    required: false
    default: 'false'
  package-manager:
    descriprion: 'Can only be npm or yarn'
    required: false
    default: 'yarn'

runs:
  using: node22
  main: 'index.js'
